framework:
    messenger:
        buses:
            command_bus:
                middleware:
                    - App\Common\Update\UpdateMiddleware
                    - doctrine_transaction
        transports:
            async:
                dsn: '%env(MESSENGER_TRANSPORT_DSN)%'
        routing:
            'App\Model\Story\Message\ModifyStoryMessage': async

services:
    messenger.middleware.doctrine_transaction:
        class: Symfony\Bridge\Doctrine\Messenger\DoctrineTransactionMiddleware
        abstract: true
        arguments: ['@doctrine']
